MODEL:
  TYPE: pss_vit
  NAME: pss
  DROP_PATH_RATE: 0.1
  VIT:
    EMBED_DIM: 768
    DEPTH: 12
    NUM_HEADS: 12
    USE_APE: False
    USE_RPB: True
    USE_SHARED_RPB: False
    USE_MEAN_POOLING: True
DATA:
  IMG_SIZE: 224
AUG:
  MIXUP: 0.0
  CUTMIX: 0.0
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 20
  BASE_LR: 1.25e-3
  WARMUP_LR: 2.5e-7
  MIN_LR: 2.5e-7
  WEIGHT_DECAY: 0.05
  LAYER_DECAY: 0.65
  PATCH_SCHEDULER:
    NAME: 'cyclic'
    START_PATCH_DROP_RATIO: 0.8
    END_PATCH_DROP_RATIO: -0.1
    COOLDOWN_EPOCHS: 0
  PATCH_DROP_FUNC: 'magnitude'
PRINT_FREQ: 100
SAVE_FREQ: 25
TAG: finetune/vit-b/magnitude_cyclic_80_0_nomix
